homepage:
    path:     /
    defaults: { _controller: HearthbreakerBundle:Default:card }

card_list:
    path: /carte
    defaults: { _controller: HearthbreakerBundle:Default:card }

card_detail:
    path: /carte/{slug}
    defaults: { _controller: HearthbreakerBundle:Default:cardDetail }

deck_list:
    path: /deck
    defaults: { _controller: HearthbreakerBundle:Default:deck }

deck_detail:
    path: /deck/{slug}
    defaults: { _controller: HearthbreakerBundle:Default:deckDetail }

user_card:
    path: /joueur/carte/{slug}/{isGolden}
    defaults: { _controller: HearthbreakerBundle:Default:userCard }
    options:
        expose: true
