parameters:
    hb.card.class: Darkwood\HearthbreakerBundle\Services\CardService
    hb.cardUnity.class: Darkwood\HearthbreakerBundle\Services\CardUnityService
    hb.deck.class: Darkwood\HearthbreakerBundle\Services\DeckService
    hb.deckCard.class: Darkwood\HearthbreakerBundle\Services\DeckCardService
    hb.userCard.class: Darkwood\HearthbreakerBundle\Services\UserCardService

services:
    hb.card:
        class: %hb.card.class%
        arguments: [@doctrine.orm.entity_manager]

    hb.cardUnity:
        class: %hb.cardUnity.class%
        arguments: [@doctrine.orm.entity_manager]

    hb.deck:
        class: %hb.deck.class%
        arguments: [@doctrine.orm.entity_manager]

    hb.deckCard:
        class: %hb.deckCard.class%
        arguments: [@doctrine.orm.entity_manager]

    hb.userCard:
        class: %hb.userCard.class%
        arguments: [@doctrine.orm.entity_manager]
