#!/usr/bin/python

# @todo : see https://github.com/dlh/youtube-dl-parallel/blob/master/youtube-dl-parallel

import os
from datetime import date
from dateutil.relativedelta import *

urls = [
	'http://www.canalplus.fr/c-divertissement/c-le-petit-journal/pid6515-l-emission.html',                  #le petit journal
	'http://www.canalplus.fr/c-divertissement/c-le-grand-journal/pid5411-le-grand-journal-l-emission.html', #le grand journal
	'http://www.canalplus.fr/c-divertissement/pid1784-c-les-guignols.html',                                 #les gigniols
	'http://www.canalplus.fr/c-divertissement/pid1787-c-groland.html',                                      #groland
	'http://www.canalplus.fr/c-infos-documentaires/pid3356-c-effet-papillon.html',                          #l'effet papillon
	'http://www.canalplus.fr/c-infos-documentaires/pid4583-c-ms-l-oeil-de-links.html',                      #l'oeil de links
	'http://www.canalplus.fr/c-infos-documentaires/pid1830-c-zapping.html',                                 #le zapping
	'http://www.youtube.com/user/LeZAPdeSpi0nOfficiel/videos',                                              #le zap de spion
	'http://www.youtube.com/user/PomfEtThud/videos',                                                        #pomf et thud
	'http://www.youtube.com/user/NormanFaitDesVideos/videos',                                               #norman
	'http://www.youtube.com/user/joueurdugrenier/videos',                                                   #joueur du grenier
	'http://www.youtube.com/user/MrAntoineDaniel/videos',                                                   #mr antoine daniel
	'http://www.youtube.com/user/smoshfrance/videos',                                                       #smosh france
	'http://www.youtube.com/user/LivelyLadder/videos',                                                      #lively ladder
	'http://www.youtube.com/user/jvcom/videos',                                                             #jvc
	'http://www.youtube.com/user/jvcomchroniques/videos',                                                   #jcv chroniques
]

for url in urls:
	cmd = './youtube-dl --dateafter now-1week -o "dl/%(upload_date)s.%(title)s.%(ext)s" --restrict-filenames --playlist-end 20 ' + url
	#os.system(cmd);

#clean dl folder : delete older videos for space
folder = 'dl'
for file in os.listdir(folder):
    path = os.path.join(folder, file)
    try:
        if os.path.isfile(path):
            uploadDate = date(int(path[3:7]),int(path[7:9]),int(path[9:11]))
            sinceDate = date.today() + relativedelta(weeks=-1, days=-1)
            if uploadDate < sinceDate:
                os.unlink(path)
    except Exception, e:
        print e
