# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    service.slack:
        class: Services\SlackService
        arguments: ['%configs%', '@service.cache']

    service.cache_adapter:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments: ['', 0, '../../var/cache/cache']

    service.cache:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments: ['@service.cache_adapter']
    
    command.autojoin:
        class: Command\AutoJoinCommand
        arguments: ['@service.slack']

    command.autoleave:
        class: Command\AutoLeaveCommand
        arguments: ['@service.slack']

    command.emoji:
        class: Command\EmojiCommand
        arguments: ['@service.slack']

    command.react:
        class: Command\ReactCommand
        arguments: ['@service.slack']

    command.tacos:
        class: Command\TacosCommand
        arguments: ['@service.slack']

    application:
        class: Symfony\Component\Console\Application
        calls:
            - [add, ['@command.autojoin']]
            - [add, ['@command.autoleave']]
            - [add, ['@command.emoji']]
            - [add, ['@command.react']]
            - [add, ['@command.tacos']]
