parameters:
    matyotools_timesheet.harvest.class: Matyotools\TimesheetBundle\Services\HarvestService

services:
    matyotools_timesheet.harvest:
        class: %matyotools_timesheet.harvest.class%
        arguments: [@harvest_app]
