parameters:
    matyotools_timesheet.harvest.class: Matyotools\TimesheetBundle\Services\HarvestService

services:
    matyotools_timesheet.harvest:
        class: %matyotools_timesheet.harvest.class%
        arguments: [@harvest_app,%matyotools_harvest_app.user%,%matyotools_harvest_app.password%,%matyotools_harvest_app.account%,%matyotools_harvest_app.mode%,%harvest_truncate_max%,%harvest_truncate_rand%]
