matyotools_domino:
    resource: "@MatyotoolsDominoBundle/Resources/config/routing.yml"
    prefix:   /

MatyotoolsTimesheetBundle:
    resource: "@MatyotoolsTimesheetBundle/Resources/config/routing.yml"
    prefix:   /