#!/bin/bash

MOVIES=.

if [ "$1" == fast ] ; then

    #http://askubuntu.com/questions/352920/fastest-way-to-convert-videos-batch-or-single
    echo 'convert movies for iphone 6s fast';
    find "$MOVIES" \( -name "*.avi" -o -name "*.mkv" -o -name "*.mp4" \) -exec sh -c 'ffmpeg -i "$0" -c:v libx264 -crf 23 -preset ultrafast -vf scale=-2:480,format=yuv420p "iphone.`basename ${0%.*}`.mp4"' {} \;

elif [ "$1" == iphone4 ] ; then

    echo 'convert movies for iphone 4';
    find "$MOVIES" \( -name "*.avi" -o -name "*.mkv" -o -name "*.mp4" \) -exec sh -c 'ffmpeg -i "$0" -vcodec h264 -q:v 1 -s 640x480 -r 24 -b:v 500k -ar 44100 -ab 128k -ac 2 -c:s mov_text "iphone.`basename ${0%.*}`.mp4"' {} \;

else

    echo 'convert movies for iphone 6s';
    find "$MOVIES" \( -name "*.avi" -o -name "*.mkv" -o -name "*.mp4" \) -exec sh -c 'ffmpeg -i "$0" -vcodec h264 -q:v 1 -s 1334x750 -r 30 -b:v 500k -ar 44100 -ab 128k -ac 2 -c:s mov_text "iphone.`basename ${0%.*}`.mp4"' {} \;

fi
