#!/bin/bash

# convert movies for iphone 4
read -d '' JS <<"JAVASCRIPT"
var path = require("path"), file = process.argv[1];
command = [
    'mv "',
    file,
    '" "',
    path.dirname(file),
    "/",
    path.basename(file)
    .toLowerCase()
    .replace(/iphone|volume-up/g,"")
    .replace(/french/g,"")
    .replace(/2013|2014/g,"")
    .replace(/avi|mkv|mp4/g,"")
    .replace(/720p|x264|hdtv|bluray/g,"")
    .replace(/-|_/g,".")
    .replace(/\\.+/g,".").replace(/^\\.+/g,"").replace(/\\.+$/g,""),
    path.extname(file),
    '"'
]
console.log(command.join(""));
JAVASCRIPT

MOVIES=.
find "$MOVIES" \( -name "*.avi" -o -name "*.mkv" -o -name "*.mp4" \) -exec node -e "$JS" {} \;
