#!/bin/bash

# log all account into messages
osascript <<EOD
  tell application "Messages"
		
		set aServiceState to status
		
		#if aServiceState is available then
		#	log out
		#end if
		
		if aServiceState is offline then
			log in
		end if
		
	end tell
EOD
