#!/bin/bash
osascript <<EOD
  tell application "Messages"
		
		set aServiceState to status
		set anApplication to application "Messages"
		
		#if aServiceState is available then
		#	tell anApplication to log out
		#end if
		
		if aServiceState is offline then
			tell anApplication to log in
		end if
		
	end tell
EOD
