#!/bin/bash

# log all account into messages, auto-join rooms
osascript <<EOD
	tell application "Messages"
		activate
		
		set aServiceState to status
		
		#if aServiceState is available then
		#	log out
		#end if
		
		if aServiceState is offline then
			log in
		end if
		
		
		repeat with c in chats
			accept c
		end repeat
		
		#set read status of every text of Messages where read status = false to true
		#set read status of every text of inbox where status = false to true
		
	end tell
EOD
