<?php

namespace Darkwood\HearthbreakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeckCardRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckCardRepository extends EntityRepository
{
}
