<?php

namespace Darkwood\HearthbreakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckRepository extends EntityRepository
{
	public function findAll()
	{
		$qb = $this->createQueryBuilder('d')
			->select('d, dc, c')
			->leftJoin('d.cards', 'dc')
			->leftJoin('dc.card', 'c')
		;

		return $qb->getQuery()->getResult();
	}

	public function findBySlug($slug)
	{
		$qb = $this->createQueryBuilder('d')
			->select('d, dc, c')
			->leftJoin('d.cards', 'dc')
			->leftJoin('dc.card', 'c')
			->andWhere('d.slug = :slug')->setParameter('slug', $slug)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findBySlugWithUser($slug, $user)
	{
		$qb = $this->createQueryBuilder('d')
			->select('d, dc, c')
			->leftJoin('d.cards', 'dc')
			->leftJoin('dc.card', 'c')
			->leftJoin('c.users', 'uc', 'with', 'uc.user = :user')
			->setParameter('user', $user)
			->andWhere('d.slug = :slug')->setParameter('slug', $slug)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}
}
