<?php

namespace Darkwood\HearthbreakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCardRepository extends EntityRepository
{
    public function findByUserAndCard($user, $card, $isGolden = null)
    {
        $qb = $this->createQueryBuilder('uc')
            ->select('uc')
            ->andWhere('uc.user = :user')->setParameter('user', $user)
            ->andWhere('uc.card = :card')->setParameter('card', $card)
        ;

        if(!is_null($isGolden)) {
            $qb->andWhere('uc.isGolden = :isGolden')->setParameter('isGolden', $isGolden);
        }

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findByUser($user, $isGolden = null)
    {
        $qb = $this->createQueryBuilder('uc')
            ->select('uc, c')
            ->leftJoin('uc.card', 'c')
            ->andWhere('uc.user = :user')->setParameter('user', $user)
        ;

        if(!is_null($isGolden)) {
            $qb->andWhere('uc.isGolden = :isGolden')->setParameter('isGolden', $isGolden);
        }

        return $qb->getQuery()->getResult();
    }

	public function findByUserAndDeck($user, $deck = null, $isGolden = null)
	{
		$qb = $this->createQueryBuilder('uc')
			->select('uc, c')
			->leftJoin('uc.card', 'c')
			->leftJoin('c.decks', 'dc')
			->andWhere('uc.user = :user')->setParameter('user', $user)
		;

		if(!is_null($deck)) {
			$qb->andWhere('dc.deck = :deck')->setParameter('deck', $deck);
		}

		if(!is_null($isGolden)) {
			$qb->andWhere('uc.isGolden = :isGolden')->setParameter('isGolden', $isGolden);
		}

		return $qb->getQuery()->getResult();
	}

	public function findOneByUserAndCard($user, $card, $isGolden = null)
	{
		$qb = $this->createQueryBuilder('uc')
			->andWhere('uc.user = :user')->setParameter('user', $user)
			->andWhere('uc.card = :card')->setParameter('card', $card)
		;

		if(!is_null($isGolden)) {
			$qb->andWhere('uc.isGolden = :isGolden')->setParameter('isGolden', $isGolden);
		}

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findAll()
	{
		$qb = $this->createQueryBuilder('uc')
			->select('uc, c, u')
			->leftJoin('uc.card', 'c')
			->leftJoin('uc.user', 'u')
		;

		return $qb->getQuery()->getResult();
	}
}
